version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbvol:/pgdata
    ports:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=adam
      - POSTGRES_DB=myfridge
      - POSTGRES_PASSWORD=adminpass1234

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    restart: always

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    restart: always

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - migrations
      - db
    environment:
      - DB_USER=adam
      - DB_NAME=myfridge
      - DB_PASSWORD=adminpass1234
      - DB_HOSTNAME=db
      - DB_PORT=5432

volumes:
  dbvol:
