version: '3'
services:
  app:
    container_name: myfridge
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - myfridge-postgres
    networks:
      - myfridge


  myfridge-postgres:
    image: postgres:latest
    container_name: myfridge_db_postgres
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
     - DATABASE_HOST=${DB_HOSTNAME}
    ports:
     - "5432:5432"
    volumes:
     - database_postgres:/var/lib/postgresql/data
    networks:
     - myfridge


volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  myfridge:
    driver: bridge