apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: myfridge
        - name: POSTGRES_PASSWORD
          value: adminfridge
        - name: POSTGRES_USER
          value: admin
        # TODO: FIX THIS PGDATA WORKAROUND FOR POSTGRES DB, I THINK THIS WILL REMAKE THE DB WHENEVER I REDEPLOY THE CONTAINER (that being said, shouldn't have to do it often, also, it doesn't really matter until I have real users!)
        - name: PGDATA
          value: /tmp
        image: postgres
        imagePullPolicy: ""
        name: db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbvol
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: dbvol
        persistentVolumeClaim:
          claimName: dbvol
status: {}
