apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: migrations
  name: migrations
spec:
  containers:
  - env:
    - name: DB_HOSTNAME
      value: db
    - name: DB_NAME
      value: myfridge
    - name: DB_PASSWORD
      value: adminfridge
    - name: DB_USER
      value: admin
    image: us.gcr.io/myfridge-280304/adampruner/my-fridge-server-migrations:0.2
    name: migrations
    resources: {}
  restartPolicy: OnFailure
status: {}
